apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"policy/v1beta1","kind":"PodDisruptionBudget","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile"},"name":"coredns-pdb","namespace":"kube-system"},"spec":{"minAvailable":1,"selector":{"matchLabels":{"k8s-app":"kube-dns"}}}}
  creationTimestamp: "2022-07-11T03:07:41Z"
  generation: 5
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
  name: coredns-pdb
  namespace: kube-system
  resourceVersion: "12579954"
  uid: 33b1af98-df66-4aef-afad-cf6802f6ab16
spec:
  minAvailable: 1
  selector:
    matchLabels:
      k8s-app: kube-dns
status:
  conditions:
  - lastTransitionTime: "2023-10-12T09:25:07Z"
    message: ""
    observedGeneration: 5
    reason: SufficientPods
    status: "True"
    type: DisruptionAllowed
  currentHealthy: 2
  desiredHealthy: 1
  disruptionsAllowed: 1
  expectedPods: 2
  observedGeneration: 5
