apiVersion: v1
kind: Pod
metadata:
  name: fiboonnodejs
  labels: 
    version: "1.0"
spec:
  containers:
  - image: xhacrtest.azurecr.cn/fiboapp:1.0.0
    name: fiboonnodejs
    ports:
    - name: fibo-port
      containerPort: 80
      protocol: TCP