apiVersion: v1
kind: Pod
metadata:
  name: python-helloworld-app
  labels: 
    version: "1.0"
spec:
  containers:
  - image: xhacrtest/python-helloworld-app:v1
    name: python-helloworld-app
    ports:
    - name: python-hw-port
      containerPort: 80
      protocol: TCP