apiVersion: v1
kind: Pod
metadata:
  name: centos-acr-wi
  labels:
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: hangwi1
  containers:
    - name: centos
      image: hangwitest.azurecr.cn/centos:v2
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo hello; sleep 10;done"]