apiVersion: v1
kind: Pod
metadata:
  name: centos
  labels:
    kubernetes.io/hostname: "aks-b2mspool-13234122-vmss000008"
spec:
   containers:
     - name: centos
       image: dockerhub.azk8s.cn/library/centos:latest
       command: ["/bin/sh"]
       args: ["-c", "while true; do echo hello; sleep 10;done"]