apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-blobv2-static-test
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-blobv2-static-test
  storageClassName: azureblob-fuse2-premium