apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-blob-static-test
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-blob-static-test
  storageClassName: azureblob-fuse-premium