apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-azure-managed-disk
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 1Gi
