# This is a SecretProviderClass example using user-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-hangwikv1-user-msi
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    userAssignedIdentityID: d86f3167-f423-42c0-baf6-f76d73da4dde   # Set the clientID of the user-assigned managed identity to use
    keyvaultName: hangwikv1        # Set to the name of your key vault
    cloudName: "AzureChinaCloud"          # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: hangsecret1
          objectType: secret              # object types: secret, key, or cert               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: hangkey1
          objectType: key
    tenantId: 954ddad8-66d7-47a8-8f9f-1316152d9587                 # The tenant ID of the key vault
