apiVersion: v1
kind: Service
metadata:
  name: ilb-fiboonnodejs
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: fiboonnodejs
